name: Phoenix ERP CI (Full Stack)

on:
  push:
    branches: ["main", "develop", "feature/*"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  # TRABAJO 1: El Backend (Lo que ya tenías)
  check-backend:
    name: Backend Build & Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend # 👈 Zona Backend

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint
      - name: Build Application
        run: npm run build

  # TRABAJO 2: El Frontend (Lo nuevo)
  check-frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend # 👈 Zona Frontend

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      # Nota: Vite hace el chequeo de tipos al compilar
      - name: Build Application
        run: npm run build
